import io
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

class PDFExportService:
    """
    Generates local, offline, high-integrity supervisory assessment PDF report
    using ReportLab. Contains zero external API or network dependencies.
    Uses neutral report branding with zero invented classification labels.
    """

    @staticmethod
    def generate_report_pdf(report_data: Dict[str, Any]) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#0f172a'), # Slate 900
            alignment=TA_LEFT,
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            'DocSubTitle',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#475569'), # Slate 600
            alignment=TA_LEFT,
            spaceAfter=12
        )
        heading2_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=13,
            leading=16,
            textColor=colors.HexColor('#1e293b'), # Slate 800
            spaceBefore=14,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyDark',
            parent=styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor('#334155')
        )
        bold_body = ParagraphStyle(
            'BoldBodyDark',
            parent=body_style,
            fontName='Helvetica-Bold'
        )

        elements = []

        meta = report_data.get("report_metadata", {})
        cse_prof = report_data.get("cse_profile", {})
        telemetry = report_data.get("telemetry_summary", {})
        signals_sum = report_data.get("supervisory_signals_summary", {})
        findings = report_data.get("active_findings", [])
        benchmarks = report_data.get("peer_baselines", [])
        capabilities = report_data.get("capability_assessment", {})
        trends = report_data.get("trends_summary", {})
        dq = report_data.get("data_quality_and_limitations", {})

        # Header Block
        elements.append(Paragraph("SAT-SA Supervisory Assessment Report", title_style))
        elements.append(Paragraph(
            f"Supervisory Analytics Tool for SOC Assessment | PS SIH 2026 26157",
            subtitle_style
        ))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceAfter=12))

        # Metadata & CSE Identity Table
        meta_table_data = [
            [
                Paragraph("<b>Report Identifier:</b>", body_style), Paragraph(str(meta.get("report_code", meta.get("report_id", ""))), body_style),
                Paragraph("<b>Generated At:</b>", body_style), Paragraph(str(meta.get("generated_at", "")), body_style)
            ],
            [
                Paragraph("<b>CSE Name (Code):</b>", body_style), Paragraph(f"{meta.get('cse_name', '')} ({cse_prof.get('code', '')})", body_style),
                Paragraph("<b>Generated By:</b>", body_style), Paragraph(str(meta.get("generated_by_user", "SUPERVISOR")), body_style)
            ],
            [
                Paragraph("<b>Sector / Criticality:</b>", body_style), Paragraph(f"{meta.get('sector', '')} | Tier {cse_prof.get('criticality_tier', '')}", body_style),
                Paragraph("<b>Observation Period:</b>", body_style), Paragraph(f"{meta.get('observation_period', {}).get('start', 'Unbounded')} to {meta.get('observation_period', {}).get('end', 'Unbounded')}", body_style)
            ]
        ]
        meta_table = Table(meta_table_data, colWidths=[110, 160, 110, 160])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
            ('PADDING', (0,0), (-1,-1), 5),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 10))

        # Section 1: Telemetry & Signals Overview
        elements.append(Paragraph("1. Executive Telemetry & Supervisory Signal Breakdown", heading2_style))
        sig_data = [
            [Paragraph("<b>Category</b>", bold_body), Paragraph("<b>Active Signals Count</b>", bold_body), Paragraph("<b>Severity Status</b>", bold_body)]
        ]
        cat_names = {
            "EXECUTION_GAP": "Execution Gaps (EG-01..EG-04)",
            "NEGATIVE_SPACE": "Negative Space Silences (NS-01, NS-02)",
            "ANOMALY": "Statistical Anomalies (AN-01)",
            "BENCHMARK": "Peer Benchmark Deviations (BM-01)"
        }
        for cat_key, cat_label in cat_names.items():
            cnt = signals_sum.get(cat_key, 0)
            sig_data.append([
                Paragraph(cat_label, body_style),
                Paragraph(str(cnt), body_style),
                Paragraph("ACTIONABLE SIGNAL" if cnt > 0 else "NO TRIGGERS", body_style)
            ])
        sig_table = Table(sig_data, colWidths=[240, 150, 150])
        sig_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        elements.append(sig_table)
        elements.append(Spacer(1, 10))

        # Section 2: Key Supervisory Findings & Explainability
        elements.append(Paragraph("2. Detailed Supervisory Findings & Explainability", heading2_style))
        if findings:
            for idx, f in enumerate(findings, 1):
                f_box = []
                f_title = f"Finding #{idx}: [{f.get('finding_code', '')}] {f.get('title', '')}"
                f_box.append(Paragraph(f"<b>{f_title}</b>", bold_body))
                f_box.append(Spacer(1, 4))

                expl = f.get("explainability", {})
                expl_data = [
                    [Paragraph("<b>WHAT:</b>", bold_body), Paragraph(str(expl.get("what", f.get("description", ""))), body_style)],
                    [Paragraph("<b>WHY:</b>", bold_body), Paragraph(str(expl.get("why", f.get("rationale", ""))), body_style)],
                    [Paragraph("<b>HOW:</b>", bold_body), Paragraph(str(expl.get("how", f.get("detection_method", ""))), body_style)],
                    [Paragraph("<b>EVIDENCE:</b>", bold_body), Paragraph(str(expl.get("evidence", f"{len(f.get('evidence', []))} records")), body_style)],
                    [Paragraph("<b>BASELINE:</b>", bold_body), Paragraph(str(expl.get("baseline", "")), body_style)],
                    [Paragraph("<b>IMPACT:</b>", bold_body), Paragraph(str(expl.get("impact", "")), body_style)],
                ]
                expl_table = Table(expl_data, colWidths=[70, 470])
                expl_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('PADDING', (0,0), (-1,-1), 3),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#f1f5f9')),
                ]))
                f_box.append(expl_table)
                f_box.append(Spacer(1, 8))
                elements.append(KeepTogether(f_box))
        else:
            elements.append(Paragraph("<i>No active supervisory findings detected for this observation window.</i>", body_style))
            elements.append(Spacer(1, 10))

        # Section 3: Eight Capability Assessment (Phase 9)
        elements.append(Paragraph("3. Eight Capability Assessment Dimensions", heading2_style))
        cap_dimensions = [
            "Threat Detection", "Investigation", "Escalation", "Incident Response",
            "Security Operations", "Governance and Oversight", "Operational Discipline", "Cyber Resilience"
        ]
        cap_table_data = [
            [Paragraph("<b>Capability Dimension</b>", bold_body), Paragraph("<b>Direct Signals</b>", bold_body), Paragraph("<b>Supervisory Status</b>", bold_body)]
        ]
        cap_signals = capabilities.get("dimensions", {})
        for c_dim in cap_dimensions:
            dim_info = cap_signals.get(c_dim, {})
            direct_cnt = dim_info.get("direct_count", 0)
            status_str = dim_info.get("status", "SATISFACTORY" if direct_cnt == 0 else "ATTENTION_REQUIRED")
            cap_table_data.append([
                Paragraph(c_dim, body_style),
                Paragraph(str(direct_cnt), body_style),
                Paragraph(status_str, body_style)
            ])
        cap_table = Table(cap_table_data, colWidths=[200, 140, 200])
        cap_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        elements.append(cap_table)
        elements.append(Spacer(1, 10))

        # Section 4: Manual Review Queue & Examiner History (Phase 11)
        elements.append(Paragraph("4. Examiner Workflow & Immutable Review History", heading2_style))
        rev_data = [
            [Paragraph("<b>Finding Code</b>", bold_body), Paragraph("<b>Status Disposition</b>", bold_body), Paragraph("<b>Examiner Note / Rationale</b>", bold_body), Paragraph("<b>Timestamp</b>", bold_body)]
        ]
        has_reviews = False
        for f in findings:
            rev_hist = f.get("review_history", [])
            for h in rev_hist:
                has_reviews = True
                rev_data.append([
                    Paragraph(f.get("finding_code", ""), body_style),
                    Paragraph(h.get("new_status", f.get("status", "")), body_style),
                    Paragraph(h.get("note_text", "-"), body_style),
                    Paragraph(str(h.get("created_at", "")), body_style),
                ])
        if has_reviews:
            rev_table = Table(rev_data, colWidths=[90, 110, 240, 100])
            rev_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                ('PADDING', (0,0), (-1,-1), 4),
            ]))
            elements.append(rev_table)
        else:
            elements.append(Paragraph("<i>No examiner review actions recorded for the findings in this report.</i>", body_style))
        elements.append(Spacer(1, 10))

        # Section 5: Data Quality & Limitations
        elements.append(Paragraph("5. Telemetry Data Quality & Limitation Audit", heading2_style))
        dq_text = [
            f"<b>Ingestion Processing Stats:</b> Total Processed Records: {dq.get('total_processed', telemetry.get('alerts_total', 0))}, Valid: {dq.get('valid_count', telemetry.get('alerts_total', 0))}, Rejected: {dq.get('rejected_count', 0)}, Duplicates Filtered: {dq.get('duplicate_count', 0)}.",
            f"<b>Evidence Distinction Audit:</b> Operational signals clearly distinguish between <i>'No evidence found'</i> (active operational telemetry present with 0 finding triggers) and <i>'Evidence of absence'</i> (telemetry silence / heartbeat monitoring gap).",
            f"<b>Coverage Limitations:</b> Evaluation scoped strictly to registered monitoring coverages and imported telemetry batches during the declared observation period."
        ]
        for t in dq_text:
            elements.append(Paragraph(t, body_style))
            elements.append(Spacer(1, 4))

        elements.append(Spacer(1, 10))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceAfter=8))
        elements.append(Paragraph("SAT-SA Automated Report Engine | Immutable Provenance Audit Verified", ParagraphStyle('Foot', parent=body_style, alignment=TA_CENTER, fontSize=8, textColor=colors.HexColor('#94a3b8'))))

        doc.build(elements)
        return buffer.getvalue()
