import uuid
from datetime import datetime
from typing import List, Dict, Any, Optional
from sqlalchemy.orm import Session
from sqlalchemy import desc, select, func

from app.models.cse import CSE
from app.models.finding import Finding, FindingEvidence
from app.services.reporting_service import ReportingService
from app.services.analytics_helpers import calculate_evidence_strength, map_rule_to_capability
from app.schemas.manual_review import ManualReviewRecommendationItem, PaginatedManualReviewResponse
from app.utils.exceptions import EntityNotFoundException

ACTIONABLE_STATUSES = {"NEW", "UNDER_REVIEW", "NEEDS_MORE_EVIDENCE"}

class ReviewService:
    """Service handling query-time Manual Review Queue derivation and recommendations."""

    @staticmethod
    def get_manual_review_queue(
        db: Session,
        cse_id: Optional[uuid.UUID] = None,
        allowed_cse_ids: Optional[List[uuid.UUID]] = None,
        record_type: Optional[str] = None,
        category: Optional[str] = None,
        status: Optional[str] = None,
        actionable_only: bool = True,
        page: int = 1,
        page_size: int = 20
    ) -> PaginatedManualReviewResponse:
        """
        Derives a Manual Review Queue of operational records linked to supervisory findings.
        Applies transparent single-column chronological ordering (detected_at DESC)
        without risk scores, priority tiers, or composite rankings.
        Enforces server-side CSE data isolation.
        """
        query = db.query(FindingEvidence).join(Finding, FindingEvidence.finding_id == Finding.id).join(CSE, Finding.cse_id == CSE.id)

        if cse_id:
            query = query.filter(Finding.cse_id == cse_id)
        elif allowed_cse_ids is not None:
            query = query.filter(Finding.cse_id.in_(allowed_cse_ids))

        if record_type:
            query = query.filter(FindingEvidence.evidence_type == record_type.upper())
        if category:
            query = query.filter(Finding.category == category.upper())
        if status:
            query = query.filter(Finding.status == status.upper())
        elif actionable_only:
            query = query.filter(Finding.status.in_(ACTIONABLE_STATUSES))

        raw_evidence_records = query.all()

        recommendations: List[ManualReviewRecommendationItem] = []
        for ev in raw_evidence_records:
            f = ev.finding
            cse_obj = f.cse

            # Determine primary record ID from linked foreign keys
            target_record_id = None
            if ev.alert_id:
                target_record_id = str(ev.alert_id)
            elif ev.case_id:
                target_record_id = str(ev.case_id)
            elif ev.investigation_id:
                target_record_id = str(ev.investigation_id)
            elif ev.escalation_id:
                target_record_id = str(ev.escalation_id)
            elif ev.coverage_id:
                target_record_id = str(ev.coverage_id)

            rule_code = (f.metrics_json.get("rule_code") if f.metrics_json else None) or "N/A"
            ev_strength = (f.metrics_json.get("evidence_strength") if f.metrics_json else None) or "LIMITED"
            capability = (f.metrics_json.get("capability") if f.metrics_json else None) or map_rule_to_capability(category=f.category, rule_code=rule_code)

            ev_count = db.query(FindingEvidence).filter(FindingEvidence.finding_id == f.id).count()
            explainability = ReportingService.build_explainability(f, ev_count)

            rec_id = f"REC-{ev.id}"
            reason_str = (
                f"Operational {ev.evidence_type} record '{target_record_id or 'N/A'}' linked to "
                f"supervisory finding '{f.title}' generated by canonical rule {rule_code}."
            )

            rec_item = ManualReviewRecommendationItem(
                recommendation_id=rec_id,
                finding_id=f.id,
                finding_code=f.finding_code,
                finding_title=f.title,
                cse_id=cse_obj.id,
                cse_code=cse_obj.cse_code,
                cse_name=cse_obj.name,
                record_type=ev.evidence_type,
                record_id=target_record_id,
                category=f.category,
                capability=capability,
                severity=f.severity,
                evidence_strength=ev_strength,
                reason=reason_str,
                review_status=f.status,
                evidence_count=ev_count,
                detected_at=f.detected_at,
                explainability=explainability
            )
            recommendations.append(rec_item)

        # Transparent chronological ordering:
        # 1. Finding detection timestamp DESC (newest existing supervisory findings first)
        # 2. Finding code ASC (deterministic technical tie-breaker without business meaning)
        sorted_recs = sorted(
            recommendations,
            key=lambda x: (
                -x.detected_at.timestamp(),
                x.finding_code
            )
        )

        total = len(sorted_recs)
        total_pages = (total + page_size - 1) // page_size if page_size > 0 else 1
        offset = (page - 1) * page_size
        paginated_items = sorted_recs[offset:offset + page_size]

        filters_applied = {
            "cse_id": str(cse_id) if cse_id else None,
            "record_type": record_type,
            "category": category,
            "status": status,
            "actionable_only": actionable_only
        }

        return PaginatedManualReviewResponse(
            items=paginated_items,
            pagination={
                "total": total,
                "page": page,
                "page_size": page_size,
                "total_pages": total_pages
            },
            filters_applied=filters_applied
        )

    @staticmethod
    def get_manual_review_recommendation_detail(
        db: Session,
        evidence_id: uuid.UUID
    ) -> ManualReviewRecommendationItem:
        """Retrieves review recommendation detail for a specific evidence record."""
        ev = db.query(FindingEvidence).filter(FindingEvidence.id == evidence_id).first()
        if not ev:
            raise EntityNotFoundException("FindingEvidence", evidence_id)

        f = ev.finding
        cse_obj = f.cse

        target_record_id = None
        if ev.alert_id:
            target_record_id = str(ev.alert_id)
        elif ev.case_id:
            target_record_id = str(ev.case_id)
        elif ev.investigation_id:
            target_record_id = str(ev.investigation_id)
        elif ev.escalation_id:
            target_record_id = str(ev.escalation_id)
        elif ev.coverage_id:
            target_record_id = str(ev.coverage_id)

        rule_code = (f.metrics_json.get("rule_code") if f.metrics_json else None) or "N/A"
        ev_strength = (f.metrics_json.get("evidence_strength") if f.metrics_json else None) or "LIMITED"
        capability = (f.metrics_json.get("capability") if f.metrics_json else None) or map_rule_to_capability(category=f.category, rule_code=rule_code)

        ev_count = db.query(FindingEvidence).filter(FindingEvidence.finding_id == f.id).count()
        explainability = ReportingService.build_explainability(f, ev_count)

        rec_id = f"REC-{ev.id}"
        reason_str = (
            f"Operational {ev.evidence_type} record '{target_record_id or 'N/A'}' linked to "
            f"supervisory finding '{f.title}' generated by canonical rule {rule_code}."
        )

        return ManualReviewRecommendationItem(
            recommendation_id=rec_id,
            finding_id=f.id,
            finding_code=f.finding_code,
            finding_title=f.title,
            cse_id=cse_obj.id,
            cse_code=cse_obj.cse_code,
            cse_name=cse_obj.name,
            record_type=ev.evidence_type,
            record_id=target_record_id,
            category=f.category,
            capability=capability,
            severity=f.severity,
            evidence_strength=ev_strength,
            reason=reason_str,
            review_status=f.status,
            evidence_count=ev_count,
            detected_at=f.detected_at,
            explainability=explainability
        )

review_service = ReviewService()
