"""phase2_initial_schema

Revision ID: 3172ce1dc800
Revises: None
Create Date: 2026-09-28 22:25:16.833429

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3172ce1dc800'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('criticality_tier', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cses_cse_code'), 'cses', ['cse_code'], unique=True)
    op.create_index(op.f('ix_cses_sector'), 'cses', ['sector'], unique=False)
    op.create_table('peer_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('peer_group', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_baselines_metric_name'), 'peer_baselines', ['metric_name'], unique=False)
    op.create_index(op.f('ix_peer_baselines_peer_group'), 'peer_baselines', ['peer_group'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('asset_identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_identifier'), 'assets', ['asset_identifier'], unique=False)
    op.create_index(op.f('ix_assets_cse_id'), 'assets', ['cse_id'], unique=False)
    op.create_table('ingestion_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('batch_reference', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('rejected_records', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_batches_batch_reference'), 'ingestion_batches', ['batch_reference'], unique=True)
    op.create_index(op.f('ix_ingestion_batches_cse_id'), 'ingestion_batches', ['cse_id'], unique=False)
    op.create_index(op.f('ix_ingestion_batches_status'), 'ingestion_batches', ['status'], unique=False)
    op.create_table('monitoring_coverages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('log_source_category', sa.String(length=100), nullable=False),
    sa.Column('is_expected', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_coverages_cse_id'), 'monitoring_coverages', ['cse_id'], unique=False)
    op.create_index(op.f('ix_monitoring_coverages_log_source_category'), 'monitoring_coverages', ['log_source_category'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('external_alert_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('target_asset_name', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_batch_id'), 'alerts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_cse_id'), 'alerts', ['cse_id'], unique=False)
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_external_alert_id'), 'alerts', ['external_alert_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_code', sa.String(length=100), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('detection_method', sa.String(length=100), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_batch_id'), 'findings', ['batch_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_cse_id'), 'findings', ['cse_id'], unique=False)
    op.create_index(op.f('ix_findings_detected_at'), 'findings', ['detected_at'], unique=False)
    op.create_index(op.f('ix_findings_finding_code'), 'findings', ['finding_code'], unique=True)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('external_case_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['ingestion_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_alert_id'), 'cases', ['alert_id'], unique=False)
    op.create_index(op.f('ix_cases_batch_id'), 'cases', ['batch_id'], unique=False)
    op.create_index(op.f('ix_cases_cse_id'), 'cases', ['cse_id'], unique=False)
    op.create_index(op.f('ix_cases_external_case_id'), 'cases', ['external_case_id'], unique=False)
    op.create_index(op.f('ix_cases_opened_at'), 'cases', ['opened_at'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('escalation_level', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_alert_id'), 'escalations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_escalations_case_id'), 'escalations', ['case_id'], unique=False)
    op.create_index(op.f('ix_escalations_escalated_at'), 'escalations', ['escalated_at'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('external_investigation_id', sa.String(length=100), nullable=True),
    sa.Column('investigator_ref', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_case_id'), 'investigations', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigations_started_at'), 'investigations', ['started_at'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('escalation_id', sa.UUID(), nullable=True),
    sa.Column('coverage_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coverage_id'], ['monitoring_coverages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidence_alert_id'), 'finding_evidence', ['alert_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_case_id'), 'finding_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_coverage_id'), 'finding_evidence', ['coverage_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_escalation_id'), 'finding_evidence', ['escalation_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_evidence_type'), 'finding_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_investigation_id'), 'finding_evidence', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_evidence_investigation_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_evidence_type'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_escalation_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_coverage_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_case_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_alert_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_investigations_started_at'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_case_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_escalations_escalated_at'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_case_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_alert_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_opened_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_external_case_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_cse_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_batch_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_alert_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_code'), table_name='findings')
    op.drop_index(op.f('ix_findings_detected_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_cse_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_batch_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_external_alert_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cse_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_batch_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_monitoring_coverages_log_source_category'), table_name='monitoring_coverages')
    op.drop_index(op.f('ix_monitoring_coverages_cse_id'), table_name='monitoring_coverages')
    op.drop_table('monitoring_coverages')
    op.drop_index(op.f('ix_ingestion_batches_status'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_cse_id'), table_name='ingestion_batches')
    op.drop_index(op.f('ix_ingestion_batches_batch_reference'), table_name='ingestion_batches')
    op.drop_table('ingestion_batches')
    op.drop_index(op.f('ix_assets_cse_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_identifier'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_peer_baselines_peer_group'), table_name='peer_baselines')
    op.drop_index(op.f('ix_peer_baselines_metric_name'), table_name='peer_baselines')
    op.drop_table('peer_baselines')
    op.drop_index(op.f('ix_cses_sector'), table_name='cses')
    op.drop_index(op.f('ix_cses_cse_code'), table_name='cses')
    op.drop_table('cses')
    # ### end Alembic commands ###
