"""add_finding_review_history_table

Revision ID: 36a474e44659
Revises: 'c3d4e5f6a7b8'
Create Date: 2026-10-02 19:03:37.993564

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36a474e44659'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_review_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('evidence_request_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_review_history_action_type'), 'finding_review_history', ['action_type'], unique=False)
    op.create_index(op.f('ix_finding_review_history_created_at'), 'finding_review_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_finding_review_history_cse_id'), 'finding_review_history', ['cse_id'], unique=False)
    op.create_index(op.f('ix_finding_review_history_finding_id'), 'finding_review_history', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_review_history_user_id'), 'finding_review_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_review_history_user_id'), table_name='finding_review_history')
    op.drop_index(op.f('ix_finding_review_history_finding_id'), table_name='finding_review_history')
    op.drop_index(op.f('ix_finding_review_history_cse_id'), table_name='finding_review_history')
    op.drop_index(op.f('ix_finding_review_history_created_at'), table_name='finding_review_history')
    op.drop_index(op.f('ix_finding_review_history_action_type'), table_name='finding_review_history')
    op.drop_table('finding_review_history')
    # ### end Alembic commands ###
