"""add_reports_table

Revision ID: 47b585f55760
Revises: 36a474e44659
Create Date: 2026-10-02 20:42:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47b585f55760'
down_revision: Union[str, None] = '36a474e44659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_code', sa.String(length=64), nullable=False),
    sa.Column('cse_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('obs_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('obs_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cse_id'], ['cses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_run_id'), 'reports', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_reports_assessment_id'), 'reports', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_reports_cse_id'), 'reports', ['cse_id'], unique=False)
    op.create_index(op.f('ix_reports_dataset_version_id'), 'reports', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_reports_report_code'), 'reports', ['report_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_code'), table_name='reports')
    op.drop_index(op.f('ix_reports_dataset_version_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_cse_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_assessment_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_run_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
